[package]
name = "dorcs_json_schema"
version = "0.2.0"
edition = "2018"

[lib]
name = "dorcs_json_schema"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8"

[build-dependencies]
schemars = "0.8"
